export const INIT_EXCHANGE_RATES = 'INIT_EXCHANGE_RATES';
export const CONVERT_RATES = 'CONVERT_RATES';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const INIT_GRAPHIC_RATES = 'INIT_GRAPHIC_RATES';